Update paho library to the latest version
eclipse-kanto/example-applications pull request #6
Opened 2023-10-10 08:40 UTC by k-gostev

[#5] Upgrade to the latest version of paho.mqtt.golang in the vehicle-simulator app

2023-10-12 08:10 UTC, hristobojilov approved these changes

2023-10-13 07:29 UTC, hristobojilov approved these changes

2023-10-19 14:19 UTC, dimitar-dimitrow requested changes
@k-gostev do we need to add the Cryptography section at the end of the NOTICE.md file as it is done for the other Kanto repos?

2023-10-19 14:19 UTC, dimitar-dimitrow commented on NOTICE.md
> +* Source:  https://cs.opensource.google/go/x/sync/+/refs/tags/v0.4.0:
```suggestion
* Source:  https://github.com/golang/sync/tree/v0.4.0
```

2023-10-20 06:25 UTC, dimitar-dimitrow approved these changes

2023-10-20 06:26 UTC, merged